//! `~/.config/tf2demos/theme.toml` → egui `Visuals`. The file is generated by the home-manager
//! module (read-only); the compiled-in default is the rice palette (HANDOFF §2), so the app
//! looks right without it.

use std::path::Path;

use anyhow::{Context, Result};
use eframe::egui::{self, Color32, CornerRadius, Stroke, Visuals};
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Theme {
    pub bg: String,
    pub panel: String,
    pub dim: String,
    pub text: String,
    pub cyan: String,
    pub pink: String,
    pub purple: String,
    pub yellow: String,
    pub green: String,
    pub blue: String,
}

impl Default for Theme {
    fn default() -> Self {
        Theme {
            bg: "#120B10".into(),
            panel: "#563466".into(),
            dim: "#6D5A78".into(),
            text: "#EEFFFF".into(),
            cyan: "#00FFC8".into(),
            pink: "#FF0055".into(),
            purple: "#D57BFF".into(),
            yellow: "#F4EF00".into(),
            green: "#00FF9C".into(),
            blue: "#76C1FF".into(),
        }
    }
}

/// The palette as egui colours, with any unparsable entry falling back to the default.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Palette {
    pub bg: Color32,
    pub panel: Color32,
    pub dim: Color32,
    pub text: Color32,
    pub cyan: Color32,
    pub pink: Color32,
    pub purple: Color32,
    pub yellow: Color32,
    pub green: Color32,
    pub blue: Color32,
}

impl Theme {
    /// Missing file → default palette; a broken file is reported and also yields the default.
    pub fn load(path: &Path) -> Theme {
        match std::fs::read_to_string(path) {
            Ok(text) => Theme::parse(&text).unwrap_or_else(|err| {
                eprintln!("tf2demos: ignoring {}: {err:#}", path.display());
                Theme::default()
            }),
            Err(_) => Theme::default(),
        }
    }

    pub fn parse(text: &str) -> Result<Theme> {
        toml::from_str(text).context("parsing theme.toml")
    }

    pub fn palette(&self) -> Palette {
        let d = Theme::default();
        let c = |hex: &str, fallback: &str| {
            parse_hex(hex).unwrap_or_else(|| parse_hex(fallback).expect("default palette parses"))
        };
        Palette {
            bg: c(&self.bg, &d.bg),
            panel: c(&self.panel, &d.panel),
            dim: c(&self.dim, &d.dim),
            text: c(&self.text, &d.text),
            cyan: c(&self.cyan, &d.cyan),
            pink: c(&self.pink, &d.pink),
            purple: c(&self.purple, &d.purple),
            yellow: c(&self.yellow, &d.yellow),
            green: c(&self.green, &d.green),
            blue: c(&self.blue, &d.blue),
        }
    }
}

/// `#RRGGBB` or `RRGGBB` (case-insensitive).
pub fn parse_hex(hex: &str) -> Option<Color32> {
    let h = hex.trim().trim_start_matches('#');
    if h.len() != 6 || !h.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    let n = u32::from_str_radix(h, 16).ok()?;
    Some(Color32::from_rgb(
        (n >> 16) as u8,
        (n >> 8 & 0xff) as u8,
        (n & 0xff) as u8,
    ))
}

impl Palette {
    /// Dark visuals: bg everywhere, sharp corners, cyan for interaction, pink for the frame —
    /// the same look as the user's mako.
    pub fn visuals(&self) -> Visuals {
        let mut v = Visuals::dark();
        let sharp = CornerRadius::ZERO;
        v.override_text_color = Some(self.text);
        v.panel_fill = self.bg;
        v.window_fill = self.bg;
        v.extreme_bg_color = self.bg;
        v.text_edit_bg_color = Some(self.bg);
        v.faint_bg_color = self.bg;
        v.code_bg_color = self.bg;
        v.window_stroke = Stroke::new(1.0, self.pink);
        v.window_corner_radius = sharp;
        v.menu_corner_radius = sharp;
        v.hyperlink_color = self.cyan;
        v.warn_fg_color = self.yellow;
        v.error_fg_color = self.pink;
        v.selection.bg_fill = self.panel;
        v.selection.stroke = Stroke::new(1.0, self.cyan);
        v.text_cursor.stroke = Stroke::new(2.0, self.cyan);

        let w = &mut v.widgets;
        w.noninteractive.bg_fill = self.bg;
        w.noninteractive.weak_bg_fill = self.bg;
        w.noninteractive.bg_stroke = Stroke::new(1.0, self.panel);
        w.noninteractive.fg_stroke = Stroke::new(1.0, self.text);
        w.inactive.bg_fill = self.panel;
        w.inactive.weak_bg_fill = self.panel;
        w.inactive.bg_stroke = Stroke::new(1.0, self.dim);
        w.inactive.fg_stroke = Stroke::new(1.0, self.text);
        w.hovered.bg_fill = self.panel;
        w.hovered.weak_bg_fill = self.panel;
        w.hovered.bg_stroke = Stroke::new(1.0, self.cyan);
        w.hovered.fg_stroke = Stroke::new(1.5, self.cyan);
        w.active.bg_fill = self.cyan;
        w.active.weak_bg_fill = self.cyan;
        w.active.bg_stroke = Stroke::new(1.0, self.cyan);
        w.active.fg_stroke = Stroke::new(2.0, self.bg);
        w.open.bg_fill = self.panel;
        w.open.weak_bg_fill = self.panel;
        w.open.bg_stroke = Stroke::new(1.0, self.cyan);
        w.open.fg_stroke = Stroke::new(1.0, self.text);
        for ws in [
            &mut w.noninteractive,
            &mut w.inactive,
            &mut w.hovered,
            &mut w.active,
            &mut w.open,
        ] {
            ws.corner_radius = sharp;
            ws.expansion = 0.0;
        }
        v
    }

    /// Apply the visuals plus slightly larger, monospace-leaning text styles.
    pub fn apply(&self, ctx: &egui::Context) {
        ctx.set_visuals(self.visuals());
        ctx.all_styles_mut(|style| {
            use egui::{FontFamily, FontId, TextStyle};
            style.text_styles = [
                (TextStyle::Heading, FontId::new(26.0, FontFamily::Monospace)),
                (TextStyle::Body, FontId::new(16.0, FontFamily::Monospace)),
                (
                    TextStyle::Monospace,
                    FontId::new(16.0, FontFamily::Monospace),
                ),
                (TextStyle::Button, FontId::new(16.0, FontFamily::Monospace)),
                (TextStyle::Small, FontId::new(12.0, FontFamily::Monospace)),
            ]
            .into();
            style.spacing.button_padding = egui::vec2(10.0, 6.0);
            style.spacing.item_spacing = egui::vec2(8.0, 8.0);
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_palette_matches_handoff() {
        let p = Theme::default().palette();
        assert_eq!(p.bg, Color32::from_rgb(0x12, 0x0B, 0x10));
        assert_eq!(p.cyan, Color32::from_rgb(0x00, 0xFF, 0xC8));
        assert_eq!(p.pink, Color32::from_rgb(0xFF, 0x00, 0x55));
        assert_eq!(p.text, Color32::from_rgb(0xEE, 0xFF, 0xFF));
        assert_eq!(p.blue, Color32::from_rgb(0x76, 0xC1, 0xFF));
    }

    #[test]
    fn parse_hex_forms() {
        assert_eq!(parse_hex("#00ffc8"), Some(Color32::from_rgb(0, 255, 200)));
        assert_eq!(parse_hex(" 00FFC8 "), Some(Color32::from_rgb(0, 255, 200)));
        assert_eq!(parse_hex("#fff"), None);
        assert_eq!(parse_hex("#00ffcg"), None);
        assert_eq!(parse_hex(""), None);
    }

    #[test]
    fn parse_partial_and_reject_unknown() {
        let t = Theme::parse("cyan = \"#123456\"\n").unwrap();
        assert_eq!(t.cyan, "#123456");
        assert_eq!(t.bg, "#120B10");
        assert!(Theme::parse("magenta = \"#000000\"").is_err());
        assert!(Theme::parse("cyan = 5").is_err());
    }

    #[test]
    fn bad_colour_falls_back_to_default() {
        let t = Theme::parse("cyan = \"nope\"\n").unwrap();
        assert_eq!(t.palette().cyan, Theme::default().palette().cyan);
    }

    #[test]
    fn load_missing_file_is_default() {
        assert_eq!(
            Theme::load(Path::new("/nonexistent/theme.toml")),
            Theme::default()
        );
    }

    #[test]
    fn visuals_are_sharp_and_dark() {
        let v = Theme::default().palette().visuals();
        assert!(v.dark_mode);
        assert_eq!(v.panel_fill, Color32::from_rgb(0x12, 0x0B, 0x10));
        assert_eq!(v.widgets.inactive.corner_radius, CornerRadius::ZERO);
        assert_eq!(v.window_stroke.color, Color32::from_rgb(0xFF, 0x00, 0x55));
        assert_eq!(
            v.override_text_color,
            Some(Color32::from_rgb(0xEE, 0xFF, 0xFF))
        );
    }
}
