//! `~/.config/tf2demos/config.toml` — read-only, generated by the home-manager module.
//!
//! The app never writes this file. When no file exists the built-in defaults apply, so the
//! tool works before the HM module installs a config.

use std::fmt;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Deserializer};

const DEFAULT_TF_DIR: &str =
    "/home/brucking/.local/share/Steam/steamapps/common/Team Fortress 2/tf";
const DEFAULT_ARCHIVE_DIR: &str = "demos/archive";
const DEFAULT_AGE_HOURS: f64 = 24.0;
const DEFAULT_GROUP_SECS: f64 = 2.0;
const DEFAULT_SEED_LABELS: &[&str] = &["surf stab", "c-tap", "matador"];
const DEFAULT_CLASSES: &[&str] = &[
    "scout", "soldier", "pyro", "demoman", "heavy", "engineer", "medic", "sniper", "spy",
];

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    /// TF2's `tf/` directory; demos live in `<tf_dir>/demos`.
    pub tf_dir: PathBuf,
    /// Archive root, relative to `tf_dir` (so `playdemo demos/archive/...` works) or absolute.
    pub archive_dir: PathBuf,
    /// A demo is a candidate for organizing once its mtime is older than this.
    #[serde(deserialize_with = "int_or_float")]
    pub age_hours: f64,
    /// Marks within this many seconds of the previous mark merge into one event.
    #[serde(deserialize_with = "int_or_float")]
    pub group_secs: f64,
    /// Copied into `index.json` on first creation; the index owns the live list afterwards.
    pub seed_labels: Vec<String>,
    /// TF2 class names offered by the labelling wizard.
    pub classes: Vec<String>,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            tf_dir: PathBuf::from(DEFAULT_TF_DIR),
            archive_dir: PathBuf::from(DEFAULT_ARCHIVE_DIR),
            age_hours: DEFAULT_AGE_HOURS,
            group_secs: DEFAULT_GROUP_SECS,
            seed_labels: DEFAULT_SEED_LABELS.iter().map(|s| s.to_string()).collect(),
            classes: DEFAULT_CLASSES.iter().map(|s| s.to_string()).collect(),
        }
    }
}

impl Config {
    /// Resolution order: explicit `path` (from `--config` / `TF2DEMOS_CONFIG`, already resolved
    /// by clap) → `$XDG_CONFIG_HOME/tf2demos/config.toml` → `$HOME/.config/tf2demos/config.toml`.
    ///
    /// An explicit path that does not exist is an error. A missing default file yields
    /// [`Config::default`]. This never writes the file.
    pub fn load(path: Option<&Path>) -> Result<Config> {
        let xdg = std::env::var_os("XDG_CONFIG_HOME")
            .filter(|v| !v.is_empty())
            .map(PathBuf::from);
        let home = std::env::var_os("HOME")
            .filter(|v| !v.is_empty())
            .map(PathBuf::from);
        Self::load_from(path, xdg.as_deref(), home.as_deref())
    }

    /// Environment-free core of [`Config::load`]: the candidate directories are passed in.
    pub fn load_from(
        explicit: Option<&Path>,
        xdg_config_home: Option<&Path>,
        home: Option<&Path>,
    ) -> Result<Config> {
        if let Some(path) = explicit {
            if !path.is_file() {
                bail!(
                    "config file {} does not exist or is not a regular file",
                    path.display()
                );
            }
            return Self::parse_file(path);
        }
        let default_path = xdg_config_home
            .map(Path::to_path_buf)
            .or_else(|| home.map(|h| h.join(".config")))
            .map(|dir| dir.join("tf2demos").join("config.toml"));
        match default_path {
            Some(path) if path.is_file() => Self::parse_file(&path),
            _ => Ok(Config::default()),
        }
    }

    fn parse_file(path: &Path) -> Result<Config> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading config {}", path.display()))?;
        Self::parse(&text).with_context(|| format!("parsing config {}", path.display()))
    }

    /// Parse TOML text. Missing keys take their defaults; unknown keys are an error.
    pub fn parse(text: &str) -> Result<Config> {
        Ok(toml::from_str(text)?)
    }

    /// `<tf_dir>/demos` — where TF2 records.
    pub fn demos_dir(&self) -> PathBuf {
        self.tf_dir.join("demos")
    }

    /// `<tf_dir>/<archive_dir>` (an absolute `archive_dir` replaces `tf_dir`).
    pub fn archive_path(&self) -> PathBuf {
        self.tf_dir.join(&self.archive_dir)
    }

    /// `<archive>/index.json` — the only mutable state.
    pub fn index_path(&self) -> PathBuf {
        self.archive_path().join("index.json")
    }

    /// `<tf_dir>/demos/_events.txt` — the master log ds appends to.
    pub fn events_master_path(&self) -> PathBuf {
        self.demos_dir().join("_events.txt")
    }
}

/// Accept `24`, `0`, or `0.5` for an `f64` field (TOML distinguishes integers from floats).
fn int_or_float<'de, D: Deserializer<'de>>(d: D) -> std::result::Result<f64, D::Error> {
    struct V;
    impl serde::de::Visitor<'_> for V {
        type Value = f64;
        fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
            f.write_str("a number (integer or float)")
        }
        fn visit_i64<E: serde::de::Error>(self, v: i64) -> std::result::Result<f64, E> {
            Ok(v as f64)
        }
        fn visit_u64<E: serde::de::Error>(self, v: u64) -> std::result::Result<f64, E> {
            Ok(v as f64)
        }
        fn visit_f64<E: serde::de::Error>(self, v: f64) -> std::result::Result<f64, E> {
            Ok(v)
        }
    }
    d.deserialize_any(V)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    fn temp_dir(tag: &str) -> PathBuf {
        static N: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "tf2demos-config-{}-{}-{}",
            std::process::id(),
            tag,
            N.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn defaults() {
        let c = Config::default();
        assert_eq!(c.tf_dir, PathBuf::from(DEFAULT_TF_DIR));
        assert_eq!(c.archive_dir, PathBuf::from("demos/archive"));
        assert_eq!(c.age_hours, 24.0);
        assert_eq!(c.group_secs, 2.0);
        assert_eq!(c.seed_labels, ["surf stab", "c-tap", "matador"]);
        assert_eq!(c.classes.len(), 9);
        assert_eq!(c.classes[0], "scout");
        assert_eq!(c.classes[8], "spy");
        assert_eq!(c.demos_dir(), PathBuf::from(DEFAULT_TF_DIR).join("demos"));
        assert_eq!(
            c.archive_path(),
            PathBuf::from(DEFAULT_TF_DIR).join("demos/archive")
        );
        assert_eq!(c.index_path(), c.archive_path().join("index.json"));
        assert_eq!(c.events_master_path(), c.demos_dir().join("_events.txt"));
    }

    #[test]
    fn parse_full_block() {
        let c = Config::parse(
            r#"
tf_dir      = "/scratch/tf"
archive_dir = "demos/archive"
age_hours   = 24
group_secs  = 2.0
seed_labels = ["surf stab", "c-tap", "matador"]
classes     = ["scout","soldier","pyro","demoman","heavy","engineer","medic","sniper","spy"]
"#,
        )
        .unwrap();
        assert_eq!(c.tf_dir, PathBuf::from("/scratch/tf"));
        assert_eq!(c.age_hours, 24.0);
        assert_eq!(c.group_secs, 2.0);
        assert_eq!(c.seed_labels.len(), 3);
        assert_eq!(c.classes.len(), 9);
    }

    #[test]
    fn absolute_archive_dir_replaces_tf_dir() {
        let c = Config::parse("archive_dir = \"/elsewhere/archive\"").unwrap();
        assert_eq!(c.archive_path(), PathBuf::from("/elsewhere/archive"));
    }

    #[test]
    fn age_hours_accepts_integer_and_float() {
        assert_eq!(Config::parse("age_hours = 0").unwrap().age_hours, 0.0);
        assert_eq!(Config::parse("age_hours = 24").unwrap().age_hours, 24.0);
        assert_eq!(Config::parse("age_hours = 0.5").unwrap().age_hours, 0.5);
        assert_eq!(Config::parse("group_secs = 3").unwrap().group_secs, 3.0);
        assert!(Config::parse("age_hours = \"24\"").is_err());
    }

    #[test]
    fn partial_file_keeps_other_defaults() {
        let c = Config::parse("age_hours = 0").unwrap();
        assert_eq!(c.tf_dir, PathBuf::from(DEFAULT_TF_DIR));
        assert_eq!(c.group_secs, 2.0);
    }

    #[test]
    fn unknown_key_errors() {
        let err = Config::parse("poll_secs = 5").unwrap_err();
        assert!(err.to_string().contains("poll_secs"), "{err}");
    }

    #[test]
    fn explicit_missing_path_errors() {
        let dir = temp_dir("missing");
        let path = dir.join("nope.toml");
        let err = Config::load_from(Some(&path), None, None).unwrap_err();
        assert!(err.to_string().contains("nope.toml"), "{err}");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn explicit_path_is_parsed() {
        let dir = temp_dir("explicit");
        let path = dir.join("config.toml");
        std::fs::write(&path, "tf_dir = \"/scratch/tf\"\nage_hours = 0\n").unwrap();
        let c = Config::load_from(Some(&path), None, None).unwrap();
        assert_eq!(c.tf_dir, PathBuf::from("/scratch/tf"));
        assert_eq!(c.age_hours, 0.0);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn missing_default_path_yields_defaults() {
        let dir = temp_dir("nodefault");
        let c = Config::load_from(None, Some(&dir), Some(&dir)).unwrap();
        assert_eq!(c.age_hours, 24.0);
        assert_eq!(c.tf_dir, PathBuf::from(DEFAULT_TF_DIR));
        let c = Config::load_from(None, None, None).unwrap();
        assert_eq!(c.age_hours, 24.0);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn xdg_then_home_resolution() {
        let xdg = temp_dir("xdg");
        let home = temp_dir("home");
        std::fs::create_dir_all(home.join(".config/tf2demos")).unwrap();
        std::fs::write(home.join(".config/tf2demos/config.toml"), "age_hours = 1").unwrap();
        // XDG dir set but has no file: XDG_CONFIG_HOME replaces ~/.config, so HOME is not consulted.
        let c = Config::load_from(None, Some(&xdg), Some(&home)).unwrap();
        assert_eq!(c.age_hours, 24.0);
        // No XDG: HOME/.config is used.
        let c = Config::load_from(None, None, Some(&home)).unwrap();
        assert_eq!(c.age_hours, 1.0);
        // XDG file present: it wins.
        std::fs::create_dir_all(xdg.join("tf2demos")).unwrap();
        std::fs::write(xdg.join("tf2demos/config.toml"), "age_hours = 2").unwrap();
        let c = Config::load_from(None, Some(&xdg), Some(&home)).unwrap();
        assert_eq!(c.age_hours, 2.0);
        std::fs::remove_dir_all(&xdg).unwrap();
        std::fs::remove_dir_all(&home).unwrap();
    }
}
